### ISSUE TITLE
耦合太高了。。没提供api，我只想对一个图片实现动画效果。却要看那么多代码

### ISSUE THREAD

**Issue by joey-wang97** [gplibs/android-magic-surface-view#3]

**Comment by gplibs** [comment]
Api就是那各种Updater，是属于较底层的api，自由度高，可以多看看README里介绍; 怎么变化全靠自己写 :)

**Comment by gplibs** [comment]
MagicSurfaceSample 中的所有代码都是例子介绍怎么写Updater，与MagicSurfaceView库没有耦合的。

**Comment by joey-wang97** [comment]
感谢




------------------ 原始邮件 ------------------
发件人: "gplibs";<notifications@github.com>;
发送时间: 2017年12月18日(星期一) 下午3:05
收件人: "gplibs/android-magic-surface-view"<android-magic-surface-view@noreply.github.com>;
抄送: "👉天宇小凡👈"<545593725@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [gplibs/android-magic-surface-view] 耦合太高了。。没提供api，我只想对一个图片实现动画效果。却要看那么多代码 (#3)




Api就是那各种Updater，是属于较底层的api，自由度高，可以多看看README里介绍; 怎么变化全靠自己写 :)
